In [4]:
try :
  import gensim.downloader as api
except Exception :
  !pip install gensim
  import gensim.downloader as api
model = api.load("word2vec-google-news-300")  # download the model and return as object ready for use

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 61.4 MB/s eta 0:00:00
[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [7]:
import torch
from torch.utils.data import Dataset,DataLoader
try :
  import tiktoken
except Excepion:
  !pip install tiktoken
  import tiktoken

In [12]:
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [16]:
import numpy as np

In [8]:
txt = "The quick brown fox jumps over the lazy dog."

In [34]:
# converting into tokens
# using simple word tokenizer
tokens = np.sort(np.array(word_tokenize(txt)))


In [37]:
d ={}
for index , token in enumerate(tokens):
  d[index] = str(token)

In [41]:
token_ids =list(d.keys())

In [47]:
temp_token_id  =token_ids[4:]

In [48]:
token_id_tensor =torch.tensor(temp_token_id )


In [49]:
token_id_tensor

tensor([4, 5, 6, 7, 8, 9])

In [56]:
vector_dim =  3 # columns
vector_size = 6  # rows

In [53]:
torch.manual_seed(12)

In [57]:
embading_layer = torch.nn.Embedding(vector_size , vector_dim)

In [59]:
embading_layer.weight # inital random weights
# each row index = one token id
# for example the first row weights : [-0.1320, -0.1254, -0.1610] refers to th weights of work with token id = 0
#  tensor([[-0.1320, -0.1254, -0.1610],  # token ID 0
#         [-0.8372, -1.2945, -0.2623],  # token ID 1
#         [-0.5353,  1.3466, -0.6958],  # token ID 2
#         [-0.0522,  0.4924, -0.6921],  # token ID 3
#         [-0.6944, -0.2125,  0.2362],  # token ID 4
#         [-1.2438,  1.4400,  0.7946]], # token ID 5
#        requires_grad=True)


Parameter containing:
tensor([[-0.1320, -0.1254, -0.1610],
        [-0.8372, -1.2945, -0.2623],
        [-0.5353,  1.3466, -0.6958],
        [-0.0522,  0.4924, -0.6921],
        [-0.6944, -0.2125,  0.2362],
        [-1.2438,  1.4400,  0.7946]], requires_grad=True)

In [66]:
# fetching embaded vector by  token id
token_id = torch.tensor([[3]]) # needed id in tensor cz embading layer in tensor
#looks for a partilar row/token id and retrives that for u
embading_layer(token_id)

tensor([[[-0.0522,  0.4924, -0.6921]]], grad_fn=<EmbeddingBackward0>)

In [ ]:
#emabding layer is also called look up table
# cz you just have to see row number for a particular token id

In [84]:
temp_token_id = [0, 1, 2]

# Convert token IDs to a LongTensor
input_tensor = torch.tensor(temp_token_id)

# Pass through embedding layer
embeddings = embading_layer(input_tensor)

print(embeddings)
print(embeddings.shape)

tensor([[-0.1320, -0.1254, -0.1610],
        [-0.8372, -1.2945, -0.2623],
        [-0.5353,  1.3466, -0.6958]], grad_fn=<EmbeddingBackward0>)
torch.Size([3, 3])
